version: '3.8'

services:
  flask:
    build: .
    container_name: line-bot-flask
    ports:
      - "5010:5010"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongo
    networks:
      - internal_network
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      internal_network:
        aliases:
          - mongo  # ✅ ให้ MongoDB มี alias เป็น "mongo"

networks:
  internal_network:
    driver: bridge

volumes:
  mongo_data: